# Generated by Django 5.2.8 on 2026-05-19 04:07

import applications.properties.models.property_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Comodidad',
                'verbose_name_plural': 'Comodidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('country', models.CharField(default='Colombia', max_length=120, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='Barrio')),
                ('address', models.CharField(max_length=220, verbose_name='Dirección')),
                ('short_description', models.CharField(max_length=240, verbose_name='Descripción corta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Capacidad')),
                ('bedrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Habitaciones')),
                ('beds', models.PositiveSmallIntegerField(default=1, verbose_name='Camas')),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Baños')),
                ('nightly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=54, max_digits=10, verbose_name='Tarifa de limpieza')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='Comodidades')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('image', models.ImageField(upload_to=applications.properties.models.property_image.upload_property_image, verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='Texto alternativo')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Portada')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de propiedad',
                'verbose_name_plural': 'Imágenes de propiedades',
                'ordering': ['-is_cover', 'created'],
            },
        ),
    ]
