# Generated by Django 5.2.8 on 2026-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('group', models.CharField(max_length=80, verbose_name='Grupo')),
                ('label_es', models.CharField(max_length=120, verbose_name='Etiqueta ES')),
                ('label_en', models.CharField(max_length=120, verbose_name='Etiqueta EN')),
                ('url', models.CharField(max_length=240, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Enlace de footer',
                'verbose_name_plural': 'Enlaces de footer',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('title_es', models.CharField(max_length=140, verbose_name='Título ES')),
                ('title_en', models.CharField(max_length=140, verbose_name='Título EN')),
                ('text_es', models.TextField(blank=True, verbose_name='Texto ES')),
                ('text_en', models.TextField(blank=True, verbose_name='Texto EN')),
                ('image', models.CharField(blank=True, max_length=240, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Beneficio de landing',
                'verbose_name_plural': 'Beneficios de landing',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='País')),
                ('image', models.CharField(max_length=240, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Destino de landing',
                'verbose_name_plural': 'Destinos de landing',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('promo', 'Promoción'), ('destinations', 'Destinos'), ('featured', 'Propiedades destacadas'), ('services', 'Servicios'), ('events', 'Eventos'), ('benefits', 'Beneficios'), ('long_stay', 'Largas estadías'), ('invest', 'Inversión')], max_length=40, unique=True, verbose_name='Sección')),
                ('eyebrow_es', models.CharField(blank=True, max_length=160, verbose_name='Eyebrow ES')),
                ('eyebrow_en', models.CharField(blank=True, max_length=160, verbose_name='Eyebrow EN')),
                ('title_es', models.CharField(max_length=180, verbose_name='Título ES')),
                ('title_en', models.CharField(max_length=180, verbose_name='Título EN')),
                ('body_es', models.TextField(blank=True, verbose_name='Cuerpo ES')),
                ('body_en', models.TextField(blank=True, verbose_name='Cuerpo EN')),
                ('cta_es', models.CharField(blank=True, max_length=80, verbose_name='CTA ES')),
                ('cta_en', models.CharField(blank=True, max_length=80, verbose_name='CTA EN')),
                ('url', models.CharField(blank=True, max_length=240, verbose_name='URL')),
                ('image', models.CharField(blank=True, max_length=240, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Sección de landing',
                'verbose_name_plural': 'Secciones de landing',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('title_es', models.CharField(max_length=120, verbose_name='Título ES')),
                ('title_en', models.CharField(max_length=120, verbose_name='Título EN')),
                ('image', models.CharField(max_length=240, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Servicio visual de landing',
                'verbose_name_plural': 'Servicios visuales de landing',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('url', models.CharField(max_length=240, verbose_name='URL')),
                ('icon', models.CharField(max_length=240, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
    ]
