# Generated by Django 5.2.8 on 2026-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraservice',
            options={'ordering': ['service_type', 'name'], 'verbose_name': 'Servicio adicional', 'verbose_name_plural': 'Servicios adicionales'},
        ),
        migrations.AddField(
            model_name='extraservice',
            name='image',
            field=models.CharField(blank=True, max_length=240, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='service_type',
            field=models.CharField(choices=[('checkin', 'Check-in flexible'), ('transport', 'Transporte'), ('fridge', 'Llena tu nevera'), ('crib', 'Cuna'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Tipo de servicio'),
        ),
    ]
