# Generated by Codex on 2026-05-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_extraservice_options_extraservice_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="user",
            new_name="guest",
        ),
    ]
